import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:kt_course/core/services/model/artist_member/artist_member.dart';
import 'package:uuid/v8.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'artist.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'artist.g.dart';

@freezed
class Artist with _$Artist {
  // ignore: invalid_annotation_target
  @JsonSerializable(explicitToJson: true)
  const factory Artist({
    required String id,
    required String name,
    required String thumbnail,
    String? description,
    required List<ArtistMember> member,
  }) = _Artist;

  static create({
    required String name,
    required String thumbnail,
    String? description,
    List<ArtistMember> member = const [],
  }) =>
      Artist(
        id: const UuidV8().generate(),
        name: name,
        thumbnail: thumbnail,
        member: member,
      );

  factory Artist.fromJson(Map<String, dynamic> json) => _$ArtistFromJson(json);
}
