import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part '{{name.lowerCase()}}.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part '{{name.lowerCase()}}.g.dart';

@freezed
class {{name.pascalCase()}} with _${{name.pascalCase()}} {

  // ignore: invalid_annotation_target
  @JsonSerializable(explicitToJson: true)
  const factory {{name.pascalCase()}}({

  }) = _{{name.pascalCase()}};

  factory {{name.pascalCase()}}.fromJson(Map<String, dynamic> json)
      => _${{name.pascalCase()}}FromJson(json);
}