import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'user.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'user.g.dart';

@freezed
class User with _$User {

  // ignore: invalid_annotation_target
  @JsonSerializable(explicitToJson: true)
  const factory User({
      required String email,
      required String name,
      required String uuid,
      String? avatar,
      String? phone,
      int? age,
      String? artistId,
      bool? ff
  }) = _User;

  // bool get isArtist => artist != null;

  factory User.fromJson(Map<String, dynamic> json)
      => _$UserFromJson(json);
}