import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'artist_member.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'artist_member.g.dart';

@freezed
class ArtistMember with _$ArtistMember {

  // ignore: invalid_annotation_target
  @JsonSerializable(explicitToJson: true)
  const factory ArtistMember({
    required String uuid,
    required String position
  }) = _ArtistMember;

  factory ArtistMember.fromJson(Map<String, dynamic> json)
      => _$ArtistMemberFromJson(json);
}